[project]
authors = ["Trevor Porter", "Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyperlane-mailbox"

[dependencies]
hyperlane_interfaces = { path = "../hyperlane-interfaces" }
hyperlane_message = { path = "../hyperlane-message" }
merkle = { path = "../merkle" }
# ownership = { git = "https://github.com/fuellabs/sway-libs", rev = "5eab914" }
ownership = { path = "/Users/trevor/.forc/git/checkouts/ownership-f6c4cb75510d36fd/5eab914a245600c9fb453b7715b92acb8015417a/libs/ownership" }
pause = { path = "../pause" }
# reentrancy = { git = "https://github.com/FuelLabs/sway-libs", rev = "5eab914" }
reentrancy = { path = "/Users/trevor/.forc/git/checkouts/reentrancy-30641758e4be7209/5eab914a245600c9fb453b7715b92acb8015417a/libs/reentrancy" }
std_lib_extended = { path = "../std-lib-extended" }
