[project]
authors = ["Trevor Porter", "Yorke Rhodes"]
entry = "main.sw"
license = "Apache-2.0"
name = "hyperlane-mailbox"

[dependencies]
hyperlane_interfaces = { path = "../hyperlane-interfaces" }
hyperlane_message = { path = "../hyperlane-message" }
merkle = { path = "../merkle" }
# ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.8.0" }
ownership = { path = "/Users/trevor/.forc/git/checkouts/ownership-f6c4cb75510d36fd/f6bb5c234e020d556e1bc688e0f1f368dc9b0f9a/libs/ownership" }
pause = { path = "../pause" }
# reentrancy = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.8.0" }
reentrancy = { path = "/Users/trevor/.forc/git/checkouts/reentrancy-30641758e4be7209/f6bb5c234e020d556e1bc688e0f1f368dc9b0f9a/libs/reentrancy" }
std_lib_extended = { path = "../std-lib-extended" }
