[workspace]

members = [
  "contracts/hyperlane-interfaces",
  "contracts/hyperlane-message",
  "contracts/hyperlane-message-test",
  "contracts/merkle",
  "contracts/merkle-test",
  "contracts/hyperlane-mailbox",
  "contracts/hyperlane-ism-test",
  "contracts/hyperlane-msg-recipient-test",
  "contracts/multisig-ism",
  "contracts/multisig-ism-metadata",
  "contracts/multisig-ism-metadata-test",
  "contracts/igp/interchain-gas-paymaster",
  "contracts/igp/overhead-igp",
  "contracts/igp/storage-gas-oracle",
  "contracts/igp/interchain-gas-paymaster-test",
  "contracts/pause",
  "contracts/pause-test",
  "contracts/validator-announce",
  "contracts/std-lib-extended",
]

[dependencies]
# ownership = { git = "https://github.com/fuellabs/sway-libs", rev = "5eab914" }
ownership = { path = "/Users/trevor/.forc/git/checkouts/ownership-f6c4cb75510d36fd/5eab914a245600c9fb453b7715b92acb8015417a/libs/ownership" }
