[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "interchain-gas-paymaster"

[dependencies]
hyperlane_interfaces = { path = "../../hyperlane-interfaces" }
# ownership = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.8.0" }
ownership = { path = "/Users/trevor/.forc/git/checkouts/ownership-f6c4cb75510d36fd/f6bb5c234e020d556e1bc688e0f1f368dc9b0f9a/libs/ownership" }
std_lib_extended = { path = "../../std-lib-extended" }
