[project]
authors = ["Yorke Rhodes", "Trevor Porter"]
entry = "lib.sw"
license = "Apache-2.0"
name = "hyperlane_interfaces"

[dependencies]
hyperlane_message = { path = "../hyperlane-message" }
# ownership = { git = "https://github.com/fuellabs/sway-libs", rev = "v0.8.0" }
ownership = { path = "/Users/trevor/.forc/git/checkouts/ownership-f6c4cb75510d36fd/f6bb5c234e020d556e1bc688e0f1f368dc9b0f9a/libs/ownership" }
