[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "validator-announce"

[dependencies]
std_lib_extended = { path = "../std-lib-extended" }
# storagemapvec = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.8.0" }
storagemapvec = { path = "/Users/trevor/.forc/git/checkouts/storagemapvec-30641758e4be7209/f6bb5c234e020d556e1bc688e0f1f368dc9b0f9a/libs/storagemapvec" }
