[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "validator-announce"

[dependencies]
std_lib_extended = { path = "../std-lib-extended" }
storagemapvec = { git = "https://github.com/fuellabs/sway-libs", tag = "v0.9.0" }
