[project]
authors = ["Trevor Porter"]
entry = "main.sw"
license = "Apache-2.0"
name = "validator-announce"

[dependencies]
std_lib_extended = { path = "../std-lib-extended" }
# storagemapvec = { git = "https://github.com/FuelLabs/sway-libs", rev = "5eab914" }
storagemapvec = { path = "/Users/trevor/.forc/git/checkouts/storagemapvec-30641758e4be7209/5eab914a245600c9fb453b7715b92acb8015417a/libs/storagemapvec" }
